import { useFocusEffect } from "expo-router";
import { useCallback,useState } from "react";
import { Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useSQLiteContext } from "expo-sqlite";
import { addGoalContribution,createGoal,deleteGoal,getGoals } from "@/database/finance";
import type { Goal } from "@/database/types";
import { formatBRL } from "@/utils/currency";

export default function Goals(){
 const db=useSQLiteContext();const [goals,setGoals]=useState<Goal[]>([]);const [name,setName]=useState("");const [target,setTarget]=useState("");const [deadline,setDeadline]=useState("");const [selected,setSelected]=useState<number|null>(null);const [contribution,setContribution]=useState("");
 const load=useCallback(async()=>setGoals(await getGoals(db)),[db]);useFocusEffect(useCallback(()=>{load()},[load]));
 const add=async()=>{const n=Number(target.replace(",","."));if(!name.trim()||!Number.isFinite(n)||n<=0){Alert.alert("Dados inválidos","Informe nome e objetivo.");return}await createGoal(db,name.trim(),n,deadline||null);setName("");setTarget("");setDeadline("");load()};
 const contribute=async()=>{const n=Number(contribution.replace(",","."));if(!selected||!Number.isFinite(n)||n<=0){return}await addGoalContribution(db,selected,n,"");setContribution("");setSelected(null);load()};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Text style={s.title}>Metas</Text><Text style={s.muted}>Crie objetivos e acompanhe seu progresso.</Text>
 <TextInput value={name} onChangeText={setName} placeholder="Nome da meta" placeholderTextColor="#666673" style={s.input}/><TextInput value={target} onChangeText={setTarget} placeholder="Valor alvo R$" placeholderTextColor="#666673" keyboardType="decimal-pad" style={s.input}/><TextInput value={deadline} onChangeText={setDeadline} placeholder="Prazo AAAA-MM-DD (opcional)" placeholderTextColor="#666673" style={s.input}/><Pressable style={s.save} onPress={add}><Text style={s.saveText}>Criar meta</Text></Pressable>
 {goals.map(g=>{const pct=Math.min(g.saved/g.target,1);return <View key={g.id} style={s.card}><View style={s.head}><View><Text style={s.name}>{g.name}</Text><Text style={s.muted}>{g.deadline?"Prazo: "+g.deadline:"Sem prazo"}</Text></View><Pressable onPress={()=>Alert.alert("Excluir meta?","As contribuições também serão removidas.",[{text:"Cancelar",style:"cancel"},{text:"Excluir",style:"destructive",onPress:async()=>{await deleteGoal(db,g.id);load();}}])}><Text style={s.delete}>Excluir</Text></Pressable></View><Text style={s.amount}>{formatBRL(g.saved)} <Text style={s.muted}>/ {formatBRL(g.target)}</Text></Text><View style={s.bar}><View style={[s.fill,{width:(pct*100)+"%"}]} /></View><View style={s.foot}><Text style={s.muted}>{Math.round(pct*100)}% concluído</Text><Pressable onPress={()=>setSelected(selected===g.id?null:g.id)} style={s.contrib}><Text style={s.contribText}>+ Contribuir</Text></Pressable></View>{selected===g.id&&<View style={s.contribRow}><TextInput value={contribution} onChangeText={setContribution} placeholder="Valor R$" placeholderTextColor="#666673" keyboardType="decimal-pad" style={s.contribInput}/><Pressable onPress={contribute} style={s.smallSave}><Text style={s.contribText}>Adicionar</Text></Pressable></View>}</View>})}
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0A0A0F"},container:{padding:20,gap:12,paddingBottom:40},title:{color:"#F7F7FA",fontSize:28,fontWeight:"800"},muted:{color:"#858592",fontSize:13},input:{backgroundColor:"#14141C",color:"#F7F7FA",padding:14,borderRadius:13},save:{backgroundColor:"#C9F23D",padding:15,borderRadius:13,alignItems:"center"},saveText:{fontWeight:"800"},card:{backgroundColor:"#14141C",borderRadius:18,padding:17,marginTop:5},head:{flexDirection:"row",justifyContent:"space-between"},name:{color:"#F7F7FA",fontSize:16,fontWeight:"800"},delete:{color:"#FF6675",fontSize:12},amount:{color:"#F7F7FA",fontSize:20,fontWeight:"800",marginTop:15},bar:{height:9,backgroundColor:"#292934",borderRadius:8,overflow:"hidden",marginTop:12},fill:{height:"100%",backgroundColor:"#C9F23D"},foot:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:10},contrib:{backgroundColor:"#25252F",paddingHorizontal:12,paddingVertical:8,borderRadius:12},contribText:{color:"#C9F23D",fontWeight:"700",fontSize:12},contribRow:{flexDirection:"row",gap:8,marginTop:10},contribInput:{flex:1,backgroundColor:"#0A0A0F",color:"#F7F7FA",padding:10,borderRadius:10},smallSave:{backgroundColor:"#25252F",paddingHorizontal:12,justifyContent:"center",borderRadius:10}});